language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
# command to install dependencies
install:
#  - pip install -r requirements.txt  # We'll need this later I think...
  - source setup/setup.sh
# command to run tests
# script: nosetests
script: tests/test_Monitor.py
