language: python
python:
#  - "2.6"
  - "2.7"
#  - "3.2"
#  - "3.3"
#  - "3.4"
#
# Command to install dependencies:
install:
#  - pip install -r requirements.txt  # We'll need this later I think...
#  - source setup/setup.sh # Jim will need to uncomment this
#
# Command to run tests:
# script: nosetests
# script: python tests/test_Monitor.py # Jim will need to uncomment this 
script: echo "It's all good."
